.class public final Lcom/dfinstagram/hooks;
.super Ljava/lang/Object;

# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static replaceReelsEndpoint(Ljava/lang/String;)Ljava/lang/String;
    .locals 1

    const-string v0, "disable_reels"

    invoke-static {v0}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v0

    if-eqz v0, :cond_return_endpoint

    const-string p0, ""

    :cond_return_endpoint
    return-object p0
.end method

.method public static throwIfBlocked(Ljava/net/URI;)V
    .locals 3

    # GENERATED by src/dfinsta_pipeline/guards.py from the url_block_rules
    # in manifest/hooks.json. Do not edit by hand: the next port regenerates it.

    if-eqz p0, :cond_return

    invoke-virtual {p0}, Ljava/net/URI;->getPath()Ljava/lang/String;

    move-result-object v0

    if-eqz v0, :cond_return

    # timeline_stream uses contains, not endsWith like its sibling. Instagram's own
    # matcher over the seven continuous-feed paths (LX/02nZ, read through
    # LX/03g2->A11 on 441) is an indexOf >= 0, so the app does not itself assume
    # the path ends at the literal. Device-measured 2026-08-08: never requested.
    const-string v1, "/feed/timeline/"

    invoke-virtual {v0, v1}, Ljava/lang/String;->endsWith(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_rule_0_toggle

    const-string v1, "/feed/timeline_stream/"

    invoke-virtual {v0, v1}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2

    if-eqz v2, :cond_rule_1

    :cond_rule_0_toggle
    const-string v1, "disable_feed"

    invoke-static {v1}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_block

    :cond_rule_1
    const-string v1, "/discover/topical_explore"

    invoke-virtual {v0, v1}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2

    if-eqz v2, :cond_rule_2

    const-string v1, "disable_explore"

    invoke-static {v1}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_block

    :cond_rule_2
    const-string v1, "/api/v1/clips/homecoming/"

    invoke-virtual {v0, v1}, Ljava/lang/String;->endsWith(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_rule_2_toggle

    const-string v1, "/clips/discover"

    invoke-virtual {v0, v1}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2

    if-eqz v2, :cond_rule_3

    :cond_rule_2_toggle
    const-string v1, "disable_reels"

    invoke-static {v1}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_block

    :cond_rule_3
    const-string v1, "/feed/reels_tray/"

    invoke-virtual {v0, v1}, Ljava/lang/String;->endsWith(Ljava/lang/String;)Z

    move-result v2

    if-eqz v2, :cond_rule_4

    const-string v1, "disable_stories"

    invoke-static {v1}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_block

    :cond_rule_4
    const-string v1, "/profile_ads/get_profile_ads/"

    invoke-virtual {v0, v1}, Ljava/lang/String;->endsWith(Ljava/lang/String;)Z

    move-result v2

    if-eqz v2, :cond_rule_5

    const-string v1, "disable_adds"

    invoke-static {v1}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_block

    :cond_rule_5
    # Reels injected into the timeline. disable_reels, not disable_feed: someone who
    # turns Reels off but keeps the feed still wants these gone.
    const-string v1, "/feed/injected_reels_media/"

    invoke-virtual {v0, v1}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2

    if-eqz v2, :cond_rule_6

    const-string v1, "disable_reels"

    invoke-static {v1}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_block

    :cond_rule_6
    const-string v1, "/feed/reels_media/"

    invoke-virtual {v0, v1}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2

    if-eqz v2, :cond_rule_7

    const-string v1, "disable_reels"

    invoke-static {v1}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_block

    :cond_rule_7
    const-string v1, "/feed/reels_media_stream/"

    invoke-virtual {v0, v1}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2

    if-eqz v2, :cond_rule_8

    const-string v1, "disable_reels"

    invoke-static {v1}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_block

    :cond_rule_8
    # Threads content in the Instagram feed. Confirmed a real request path: LX/03hm,
    # the Tigon layer that matches literals against URI.getPath().
    const-string v1, "/feed/text_post_app_timeline/"

    invoke-virtual {v0, v1}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v2

    if-eqz v2, :cond_return

    const-string v1, "disable_feed"

    invoke-static {v1}, Lcom/dfinstagram/dfinstagram;->getBoolTrueEz(Ljava/lang/String;)Z

    move-result v2

    if-nez v2, :cond_block

    :cond_return
    return-void

    :cond_block
    new-instance v0, Ljava/io/IOException;

    const-string v1, "Blocked by DFInsta setting"

    invoke-direct {v0, v1}, Ljava/io/IOException;-><init>(Ljava/lang/String;)V

    throw v0
.end method
